#!/usr/bin/env node
/**
 * generate-icons — build/icon.svg 로부터 platform 별 아이콘 생성.
 *
 * 사용:
 *   node scripts/generate-icons.cjs
 *
 * 생성 파일:
 *   - build/icon.png  (1024×1024) — Linux + macOS source (electron-builder 가
 *                                    자동으로 ICNS 변환).
 *   - build/icon.ico  — Windows installer 아이콘 (multi-size: 16,32,48,64,128,256).
 *
 * macOS ICNS 는 본 script 가 직접 생성하지 않음 — electron-builder 가 빌드 시
 * PNG 1024 로부터 자동 변환. Apple iconutil/sips 같은 macOS 전용 도구 의존성
 * 회피.
 *
 * SVG 변경 시 manual 재생성 후 commit.
 *
 * Note: png-to-ico v3+ 는 ESM-only — dynamic import() 로 로드.
 *
 * Spec: docs/release.md (플랫폼 아이콘 자동 생성)
 */
const { Resvg } = require('@resvg/resvg-js');
const { readFileSync, writeFileSync } = require('node:fs');
const { join } = require('node:path');

const buildDir = join(__dirname, '..', 'build');
const svgPath = join(buildDir, 'icon.svg');
const pngPath = join(buildDir, 'icon.png');
const icoPath = join(buildDir, 'icon.ico');

async function main() {
  console.log('[generate-icons] Reading SVG:', svgPath);
  const svg = readFileSync(svgPath);

  // === 1. PNG (1024×1024) — Linux + macOS source ===
  console.log('[generate-icons] Rendering PNG (1024×1024)...');
  const png1024 = new Resvg(svg, {
    fitTo: { mode: 'width', value: 1024 },
  })
    .render()
    .asPng();
  writeFileSync(pngPath, png1024);
  console.log(`[generate-icons] OK ${pngPath} (${png1024.length} bytes)`);

  // === 2. ICO (multi-size) — Windows installer ===
  // png-to-ico 의 default export 는 Buffer[] 를 받아 ICO 컨테이너 빌드.
  // ESM-only 라 dynamic import() 사용.
  console.log('[generate-icons] Rendering ICO sizes [16, 32, 48, 64, 128, 256]...');
  const icoSizes = [16, 32, 48, 64, 128, 256];
  const icoBuffers = icoSizes.map((size) => {
    const buf = new Resvg(svg, {
      fitTo: { mode: 'width', value: size },
    })
      .render()
      .asPng();
    return Buffer.from(buf);
  });

  const pngToIcoModule = await import('png-to-ico');
  const pngToIco = pngToIcoModule.default;
  const ico = await pngToIco(icoBuffers);
  writeFileSync(icoPath, ico);
  console.log(`[generate-icons] OK ${icoPath} (${ico.length} bytes)`);
  console.log('[generate-icons] Done.');
  console.log(
    '[generate-icons] Note: macOS ICNS auto-generated by electron-builder from icon.png at build time.'
  );
}

main().catch((err) => {
  console.error('[generate-icons] Failed:', err);
  process.exit(1);
});
